name: Kanban CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.added.* || github.event.head_commit.modified.* || github.event.head_commit.removed.* }} && contains(join(github.event.head_commit.modified, ' '), 'backend/') || contains(join(github.event.head_commit.added, ' '), 'backend/') || contains(join(github.event.head_commit.removed, ' '), 'backend/')
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Load environment variables
        run: echo "Loading backend secrets"
        env:
          MONGO_URI: ${{ secrets.BACKEND_MONGO_URI }}

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.added.* || github.event.head_commit.modified.* || github.event.head_commit.removed.* }} && contains(join(github.event.head_commit.modified, ' '), 'frontend/') || contains(join(github.event.head_commit.added, ' '), 'frontend/') || contains(join(github.event.head_commit.removed, ' '), 'frontend/')
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Load environment variables
        run: echo "Loading frontend secrets"
        env:
          VITE_API_URL: ${{ secrets.FRONTEND_API_URL }}

      - name: Run Prettier
        run: npm run format

      - name: Run ESLint
        run: npm run lint
